/* Rialuecho_ctx
 * Authors: Arthur Pires, Josenildo Vicente, Renato Joaquim
 * Creation date: 07/03/2021
 */
MACHINE
    Rialuecho_ctx
SETS
    num_carrinho = {
        num_carrinho0 ,
        num_carrinho1 ,
        num_carrinho2 ,
        num_carrinho3 ,
        num_carrinho4
    } ;
    ids_produto = {
        ids_produto0 ,
        ids_produto1 ,
        ids_produto2 ,
        ids_produto3 ,
        ids_produto4
    }
END
